class Strings {
  static const appTitle = "Evier - Sanitary shopping application";
  static const title = "Evier";
  static const categoryTitle = "Category";
  static const favouriteTitle = "Favourite";
  static const accountTitle = "Account";
  static const createAccount = "Create Account";
  static const signInWithGoogle = "Sign in with Google";
  static const login = "Login";
  static const categoryFloorTrap = "Floor Trap";
  static const logout = "Logout";
  static const addProduct = "Add Product";
  static const emailHint = "Email";
  static const emailError = "Please enter the email";
  static const passwordHint = "Password";
  static const passwordError = "Please enter the password";
  static const register = "Register";
  static const goToLoginPage = "Go to login page";
  static const search = "Search";
  static const productNameHint = "Product Name";
  static const productNameError = "Please enter the product name";
  static const priceHint = "Price";
  static const priceError = "Please enter the product price";
  static const categoryError = "Please select the category";
  static const companyTitle = "Company";
  static const companyError = "Please select the company";
  static const productDescription = "Description";
  static const productDescriptionError = "Please enter the product description";
}
